import React,{useState}from'react';import{createRoot}from'react-dom/client';import{PDFDocument,rgb,StandardFonts}from'pdf-lib';import{Upload,Download,Lock,Plus,Trash2}from'lucide-react';import'./style.css';
const hash=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(b=>b.toString(16).padStart(2,'0')).join('');
function App(){const[file,setFile]=useState(null),[url,setUrl]=useState(''),[pw,setPw]=useState(''),[locked,setLocked]=useState(false),[unlocked,setUnlocked]=useState(true),[items,setItems]=useState([]),[text,setText]=useState('');
async function load(e){let f=e.target.files[0];if(!f)return;setFile(f);setUrl(URL.createObjectURL(f));setItems([]);setPw('');setLocked(false);setUnlocked(true)}
async function protect(){if(!file||!pw)return alert('Escolhe um PDF e define uma password.');localStorage.setItem('rjp:'+file.name,await hash(pw));setLocked(true);setUnlocked(true);alert('Password associada a este ficheiro neste dispositivo.')}
async function unlock(){let h=localStorage.getItem('rjp:'+file.name);if(!h||await hash(pw)===h){setUnlocked(true)}else alert('Password incorreta.')}
function add(){if(text.trim()){setItems([...items,{text,x:50,y:50,size:14}]);setText('')}}
async function save(){if(!file)return;let bytes=await file.arrayBuffer(),doc=await PDFDocument.load(bytes),page=doc.getPages()[0],font=await doc.embedFont(StandardFonts.Helvetica);items.forEach((i,n)=>page.drawText(i.text,{x:i.x,y:page.getHeight()-i.y-20*n,size:i.size,font,color:rgb(0,0,0)}));let out=await doc.save(),blob=new Blob([out],{type:'application/pdf'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file.name.replace(/\.pdf$/i,'')+'_editado.pdf';a.click()}
return <main><header><div><b>RJP</b> PDF Editor</div><small>PDF local • sem upload para servidor</small></header><section className="toolbar"><label className="btn"><Upload size={18}/> Abrir PDF<input hidden type="file" accept="application/pdf" onChange={load}/></label><input type="password" placeholder="Password do ficheiro" value={pw} onChange={e=>setPw(e.target.value)}/><button onClick={protect}><Lock size={17}/> Proteger</button>{locked&&!unlocked&&<button onClick={unlock}>Desbloquear</button>}<button className="primary" onClick={save}><Download size={17}/> Guardar PDF</button></section>{file?<section className="workspace"><aside><h3>Adicionar texto</h3><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Texto a inserir..."/><button onClick={add}><Plus size={17}/> Adicionar</button><h3>Elementos</h3>{items.map((i,n)=><div className="item" key={n}>{i.text}<Trash2 size={16} onClick={()=>setItems(items.filter((_,x)=>x!==n))}/></div>)}<p className="note">V0.1: adiciona texto sobre o PDF e exporta um novo ficheiro. A edição direta do texto interno do PDF fica preparada para evolução.</p></aside><div className="viewer">{(!locked||unlocked)?<iframe src={url}/>:<div className="locked"><Lock size={48}/><h2>Documento protegido</h2></div>}</div></section>:<div className="empty"><Upload size={60}/><h2>Abre um PDF para começar</h2><p>O documento é processado localmente no browser.</p></div>}</main>}
createRoot(document.getElementById('root')).render(<App/>);
