import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import * as pdfjsLib from 'pdfjs-dist';
import {PDFDocument,PDFTextField,PDFCheckBox} from 'pdf-lib';
import {FileUp,Save,Download,RotateCcw,Type,Trash2,ChevronLeft,ChevronRight,Mic} from 'lucide-react';
import './style.css';
pdfjsLib.GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/build/pdf.worker.min.mjs',import.meta.url).toString();
const TEMPLATE_URL=`${import.meta.env.BASE_URL}templates/Ficha_Atendimento_EDITAVEL_RJP.pdf`;
const RJP='RJP_EDIT_';
function App(){
 const [bytes,setBytes]=useState(null),[name,setName]=useState('documento.pdf'),[docjs,setDocjs]=useState(null),[page,setPage]=useState(1),[scale,setScale]=useState(1.35),[vp,setVp]=useState(null),[fields,setFields]=useState([]),[values,setValues]=useState({}),[addMode,setAddMode]=useState(false),[selected,setSelected]=useState(null),[status,setStatus]=useState('A carregar ficha base…');
 const canvas=useRef(null);
 useEffect(()=>{loadTemplate()},[]); useEffect(()=>{if(docjs)render()},[docjs,page,scale]);
 async function loadTemplate(){const b=new Uint8Array(await(await fetch(TEMPLATE_URL)).arrayBuffer());await load(b,'Ficha_Atendimento_RJP.pdf')}
 async function load(b,n){try{setStatus('A abrir PDF real…');const safe=new Uint8Array(b);const d=await pdfjsLib.getDocument({data:safe.slice()}).promise;setDocjs(d);setBytes(safe);setName(n);setPage(1);await readFields(safe);setStatus(`PDF aberto: ${d.numPages} páginas. Podes editar campos e adicionar novos textos.`)}catch(e){console.error(e);setStatus('Erro ao abrir PDF.') }}
 async function readFields(b){const d=await PDFDocument.load(b,{ignoreEncryption:true});const form=d.getForm();const arr=[],vals={};for(const f of form.getFields()){const fn=f.getName();try{if(f instanceof PDFTextField)vals[fn]=f.getText()||'';else if(f instanceof PDFCheckBox)vals[fn]=f.isChecked()}catch{};try{for(const w of f.acroField.getWidgets()){const r=w.getRectangle();const pref=w.P()?.asNumber?.();let pi=0;if(pref){const ps=d.getPages();pi=ps.findIndex(p=>p.ref.objectNumber===pref)}if(pi<0)pi=0;arr.push({name:fn,type:f instanceof PDFCheckBox?'checkbox':'text',page:pi+1,rect:[r.x,r.y,r.x+r.width,r.y+r.height],rjp:fn.startsWith(RJP)})}}catch{}}
 setFields(arr);setValues(vals)}
 async function render(){const p=await docjs.getPage(page),v=p.getViewport({scale});setVp(v);const c=canvas.current;if(!c)return;c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);c.style.width=v.width+'px';c.style.height=v.height+'px';await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise}
 const style=f=>{if(!vp)return{};const[x1,y1,x2,y2]=f.rect,s=vp.scale;return{left:x1*s,top:vp.height-y2*s,width:(x2-x1)*s,height:(y2-y1)*s}};
 function upd(k,v){setValues(x=>({...x,[k]:v}))}
 function clickPaper(e){if(!addMode||!vp)return;const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/vp.scale,y=(vp.height-(e.clientY-r.top))/vp.scale;const fn=RJP+Date.now();const f={name:fn,type:'text',page,rect:[x,y-4,x+180,y+15],rjp:true};setFields(a=>[...a,f]);setValues(v=>({...v,[fn]:''}));setSelected(fn);setAddMode(false);setStatus('Novo campo criado. Escreve o texto e podes voltar a editar depois de guardar.')}
 function removeSelected(){if(!selected)return;setFields(a=>a.filter(f=>f.name!==selected));setValues(v=>{const n={...v};delete n[selected];return n});setSelected(null)}
 async function save(as=false){try{setStatus('A guardar sobre o PDF original, sem rasterizar páginas…');const d=await PDFDocument.load(bytes.slice(),{ignoreEncryption:true});const form=d.getForm(),pages=d.getPages(),existing=new Set(form.getFields().map(f=>f.getName()));
 // remove RJP fields deleted in UI
 for(const f of form.getFields()){if(f.getName().startsWith(RJP)&&!fields.some(x=>x.name===f.getName()))try{form.removeField(f)}catch{}}
 for(const f of fields){let fld;try{fld=form.getField(f.name)}catch{};if(!fld&&f.rjp){fld=form.createTextField(f.name);const[x1,y1,x2,y2]=f.rect;fld.addToPage(pages[f.page-1],{x:x1,y:y1,width:x2-x1,height:y2-y1,borderWidth:0});try{fld.setFontSize(10)}catch{}}
 if(!fld)continue;try{if(fld instanceof PDFTextField)fld.setText(String(values[f.name]??''));else if(fld instanceof PDFCheckBox){values[f.name]?fld.check():fld.uncheck()}}catch{}}
 const out=await d.save({useObjectStreams:false,updateFieldAppearances:true});let nn=name;if(as){const q=prompt('Nome do novo PDF:',name.replace(/\.pdf$/i,'')+'_editado.pdf');if(!q){setStatus('Cancelado.');return}nn=q.toLowerCase().endsWith('.pdf')?q:q+'.pdf'}const blob=new Blob([out],{type:'application/pdf'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=nn;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);setBytes(new Uint8Array(out));setName(nn);await readFields(new Uint8Array(out));setStatus('PDF guardado. O conteúdo original foi preservado e os campos RJP continuam editáveis.')}catch(e){console.error(e);setStatus('Erro ao guardar: '+(e.message||e))}}
 async function openFile(e){const f=e.target.files?.[0];if(f){await load(new Uint8Array(await f.arrayBuffer()),f.name);e.target.value=''}}
 function dictate(k){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setStatus('Usa o microfone do Gboard/teclado neste campo.');return}const r=new SR();r.lang='pt-PT';r.onresult=e=>upd(k,(values[k]||'')+(values[k]?' ':'')+e.results[0][0].transcript);r.start()}
 return <div className="app"><header><div className="brand"><div className="logo">RJP</div><div><strong>PDF Editor</strong><small>V1.2 — edição persistente do próprio PDF</small></div></div><div className="actions"><label className="btn secondary"><FileUp size={17}/> Abrir PDF<input type="file" accept="application/pdf" onChange={openFile}/></label><button className="btn secondary" onClick={loadTemplate}><RotateCcw size={17}/> Ficha base</button><button className={'btn secondary '+(addMode?'active':'')} onClick={()=>setAddMode(x=>!x)}><Type size={17}/> Adicionar texto</button><button className="btn secondary" disabled={!selected} onClick={removeSelected}><Trash2 size={17}/> Apagar campo</button><button className="btn" onClick={()=>save(false)}><Save size={17}/> Guardar</button><button className="btn" onClick={()=>save(true)}><Download size={17}/> Guardar como…</button></div></header><div className="status">{status}</div><main><aside><div className="sideTitle">Campos editáveis — pág. {page}</div><div className="fieldList">{fields.filter(f=>f.page===page).map((f,i)=><div className={'fieldRow '+(selected===f.name?'sel':'')} key={f.name} onClick={()=>setSelected(f.name)}><label>{f.rjp?'Texto RJP '+(i+1):f.name}</label>{f.type==='checkbox'?<input type="checkbox" checked={!!values[f.name]} onChange={e=>upd(f.name,e.target.checked)}/>:<div className="textCtl"><input value={values[f.name]||''} onChange={e=>upd(f.name,e.target.value)}/><button onClick={()=>dictate(f.name)}><Mic size={14}/></button></div>}</div>)}</div></aside><section className="viewer"><div className="pager"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft/></button><span>Página <b>{page}</b> / {docjs?.numPages||1}</span><button disabled={!docjs||page>=docjs.numPages} onClick={()=>setPage(p=>p+1)}><ChevronRight/></button><select value={scale} onChange={e=>setScale(+e.target.value)}><option value="1">100%</option><option value="1.2">120%</option><option value="1.35">135%</option><option value="1.6">160%</option></select></div><div className={'paper '+(addMode?'addMode':'')} style={vp?{width:vp.width,height:vp.height}:undefined} onClick={clickPaper}><canvas ref={canvas}/>{vp&&fields.filter(f=>f.page===page).map(f=>f.type==='checkbox'?<input key={f.name} className="overlayCheck" style={style(f)} type="checkbox" checked={!!values[f.name]} onClick={e=>e.stopPropagation()} onChange={e=>upd(f.name,e.target.checked)}/>:<input key={f.name} className={'overlayInput '+(selected===f.name?'selected':'')} style={style(f)} value={values[f.name]||''} onClick={e=>{e.stopPropagation();setSelected(f.name)}} onChange={e=>upd(f.name,e.target.value)}/>)}</div></section></main></div>}
createRoot(document.getElementById('root')).render(<App/>);
